//
// Created by marco on 2/17/22.
//

#include "splash.h"
#include <stdio.h>
using namespace std;

void splash::welcome(){
    printf("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKc.'oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n"
           "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk'    cXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n"
           "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd.      ;KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n"
           "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKc         ,0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n"
           "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0,           'OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n"
           "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk.             .kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n"
           "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd.               .xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n"
           "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXl.                 .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n"
           "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXc                    .dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n"
           "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWK:                      .oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n"
           "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0;                        .dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n"
           "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO,                          .l0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n"
           "MMMMMMMMMMMMMMMMMMMMMMMMMMMMNKkoc,.                              .,cokKWMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n"
           "MMMMMMMMMMMMMMMMMMMMMMMMWKxc,.                                        .,cxKWMMMMMMMMMMMMMMMMMMMMMMMM\n"
           "MMMMMMMMMMMMMMMMMMMMMNOl,.                                        .,.     .,oONMMMMMMMMMMMMMMMMMMMMM\n"
           "MMMMMMMMMMMMMMMMMMNOl,     ':do.                                  'kXOd:.     ,o0WMMMMMMMMMMMMMMMMMM\n"
           "MMMMMMMMMMMMMMMMXd;.    ,lOXW0,                                    '0MMWXOl,    .;xXMMMMMMMMMMMMMMMM\n"
           "MMMMMMMMMMMMMMKo.    'lONWMMK;                                      ;KMMMMMNOl'    'oKWMMMMMMMMMMMMM\n"
           "MMMMMMMMMMWWKl.   .;kNMMWMMK;                                        cNMMMMMMMXx;    .oKMMMMMMMMMMMM\n"
           "MMMMMMMMMMXd.   .:OWMMMMMMX:                                         .oNMMMMMMMMNO:.   'dNMMMMMMMMMM\n"
           "MMMMMMMMWO,   .:OWMMMMMMMNc                                           .kWMMMMMMMMWWO;    ,OWMWWMMMMM\n"
           "MMMMMMWXo.   ,kNMMMMMMMMWo.                                            '0MMMMMMMMMMMNk,   .oXMWMMMMM\n"
           "MMMMMW0;   .lXMMMMMMMMMWx.                                              :XMMMMMMMMMMMMXl.   :KMMMMMM\n"
           "MMMMWO'   .kWMMMMMMMMMMO.                                                oWMMWMMMMMMMMMWx.   ,OWMMMM\n"
           "MMMWk.   ,0MMMMMMMMMMM0,                                                 .OMMMMMMMMMMMMMW0,   'OWMMM\n"
           "MMMO.   ;KMMMMMMMMMMMX:                                                   ;XMMMMMMMMMMMMMM0,   'OMMM\n"
           "MM0,   ,KMMMMMMMMMMMNo                                                     oWMMMMMMMMMMMMMM0,   ,0MM\n"
           "MX:   'OMMMMMMMMMMMWx.                                                     .OMMMMMMMMMMMMMMWO'   cXM\n"
           "Wd.  .dWMMMMMMMMMMM0'                                                       :NMMMMMMMMMMMMMMWd.  .dW\n"
           "K,   cNMMMMMMMMMMMX:                                                        .xWMMMMMMMMMMMMMMN:   ,K\n"
           "d   .kMMMMMMMMMMMWo                                                          ;KMMMMMMMMMMMMMMMk.  .d\n"
           ";   cNMMMMMMMMMMMO.                                                           oWMMMMMMMMMMMMMMX:   ;\n"
           ".   dMMMMMMMMMMMX;                                                            '0MMMMMMMMMMMMMMMd   .\n"
           "   .OMMMMMMMMMMWo                                                              oWMMMMMMMMMMMMMMk.   \n"
           "   '0MMMMMMMMMMO.                                                              '0MMMMMMMMMMMMMM0'   \n"
           "   ,KMMMMMMMMMX:                                                                lWMMMMMMMMMMMMMK,   \n"
           "   ,KMMMMMMMMWd.                                                                '0MMMMMMMMMMMMMK,   \n"
           "   '0MMMMMMMM0'                                                                  oWMMMMMMMMMMMMO'   \n"
           ".  .kMMMMMMMWl                                                                   '0MMMMMMMMMMMMk.  .\n"
           ".   oWMMMMMMO.                                                                    oWMMMMMMMMMMWl   '\n"
           ":   ;XMMMMMNc                                                                     ;KMMMMMMMMMMK,   c\n"
           "x.  .xMMMMMk.                                                                     .xMMMMMMMMMWd.  .k\n"
           "X:   ;KMMMX:                                                                       :NMMMMMMMMK,   :X\n"
           "Mk.   lNMMx.                                                                       .OMMMMMMMNl   .OM\n"
           "MWo   .dWX:                                                  ...                    oWMMMMMWd.  .oWM\n"
           "MMXc   .xx.                                           .';ldk0KXKkc.                 ,KMMMMWx.   cNMM\n"
           "MMMK:   ..                                       .',lx0NWMMMMMMMMWXd,               .xMMMWx.   :XMMM\n"
           "MMMMK:                                        'cxKNWMMMMMMMMMMMMMMMMNk,              cNMNd.   :XMMMM\n"
           "MMMMMXc                                    'ckXMMMMMMMMMMMMMMMMMMMMMMMXd.            'OKc.  .cXMMMMM\n"
           "MMMMMWNl                                .:kXMMMMMMMMMMMMMMMMMMMMMMMMMMMW0:            ;,   .dNMMMMMM\n"
           "MMMMMMWd                              ,dKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNx.              ,OWMMMMMMM\n"
           "MMMMMMX;                           .:kNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0;           .oXMMMMMMMMM\n"
           "MMMMMMk.                         .l0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXl.        ,0WMMMMMMMMMM\n"
           "MMMMMWl                        'oXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX:        ;XMMMMMMMMMMM\n"
           "MMMMMK,                      'dXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNOl,         .OMMMMMMMMMMM\n"
           "MMMMMk.                    .cXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXkl'    .,'      oWMMMMMMMMMM\n"
           "MMMMWl                      .;lkKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWN0xl;.    .,oONXc     ;XMMMMMMMMMM\n"
           "MMMMX;                 .:;.     .':ldk0XNWMMMMMMMMMMMMMMMWWNK0kdl;'.     .;oONMMWMXl.   .OMMMMMMMMMM\n"
           "MMMMO.               .lKWWXko;'.      ..',;:clloooooollcc;,'..      ..;okXWMMMMMMMMNo.   oWMMMMMMMMM\n"
           "MMMMd              .:0WMMMMMMWN0xo:,..                        ..,cox0NWMMMMMMMMMMMMMWx.  :NMMMMMMMMM\n"
           "MMMNc             ,kNMMMMMMMMMMMMMMWXKOxdolc::;;;,,,;;::clodkOKNWMMMMMMMMMMMMMMMMMMMMWx. 'OMMMMMMMMM\n"
           "MMMK,           .dXWMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk..dMMMMMMMMM\n"
           "MMMk.         .cKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO'cNMMMMMMMM\n"
           "MMMd         ;OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOl0MMMMMMMM\n"
           "MMWl       .dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXXMMMMMMMM\n"
           "MMX;     .cKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n"
           "MM0'    ,kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n"
           "MMk.  .oXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n"
           "MMx. ;OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n"
           "MWo.dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n"
           "MWkkWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n");

    printf("#     #                                 #####                                  #####                                                #####                                   \n"
           "##   ##   ##   #    # ###### #####     #     # #####    ##    ####  ######    #     #  ####    ##   #    # #    # ###### #####     #     # #   #  ####  ##### ###### #    # \n"
           "# # # #  #  #  #   #  #      #    #    #       #    #  #  #  #    # #         #       #    #  #  #  ##   # ##   # #      #    #    #        # #  #        #   #      ##  ## \n"
           "#  #  # #    # ####   #####  #    #     #####  #    # #    # #      #####      #####  #      #    # # #  # # #  # #####  #    #     #####    #    ####    #   #####  # ## # \n"
           "#     # ###### #  #   #      #####           # #####  ###### #      #               # #      ###### #  # # #  # # #      #####           #   #        #   #   #      #    # \n"
           "#     # #    # #   #  #      #   #     #     # #      #    # #    # #         #     # #    # #    # #   ## #   ## #      #   #     #     #   #   #    #   #   #      #    # \n"
           "#     # #    # #    # ###### #    #     #####  #      #    #  ####  ######     #####   ####  #    # #    # #    # ###### #    #     #####    #    ####    #   ###### #    # \n");

    return;
}